services:
  db:
    image: postgres:12.19-alpine3.19
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=mydb
    volumes:
    - ./sqls:/docker-entrypoint-initdb.d